# Media type definitions
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[mediaTypes."application/xslt+xml"]
  suffixes = ["xsl"]

# Output format definitions
[outputFormats.ATOM]
  mediaType = "application/atom+xml"
  baseName = "atom"
  name = "ATOM"

[outputFormats.sitemapxsl]
  mediaType = "application/xslt+xml"
  baseName = "sitemap"
  isPlainText = true
  notAlternative = true

[outputFormats.feedxsl]
  mediaType = "application/xslt+xml"
  baseName = "feed"
  isPlainText = true
  notAlternative = true

[outputFormats.REDIR]
  mediaType = "text/plain"
  baseName = "redirects"
  isPlainText = true
  notAlternative = true

[outputFormats.SECURITY]
  mediaType = "text/plain"
  baseName = "security"
  isPlainText = true
  notAlternative = true
  path = ".well-known"
