baseURL = 'https://example.org/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    identifier = 'home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    identifier = 'tags'
    pageRef = '/tags'
    weight = 20

[markup.highlight]
  noClasses = false

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$']]
    inline = [['\(', '\)']]

[params]
  # Remark42 comment system configuration (optional)
  # Uncomment and configure these to enable the comment system
  # remarkURL = "https://remark.example.com"
  # remarkSiteId = "remark"
  # remarkLocale = "zh"
  # remarkNoFooter = "true"

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
