<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:output method="html" encoding="UTF-8"/>

    <xsl:template match="/">
        <html{{ with .Site.Params.lang }} lang="{{ . }}"{{ end }}>
            <head>
                <title>XML Sitemap</title>
                <style type="text/css">
                    body {
                        font-family: Lora, "Noto Serif SC", serif;
                        font-size: 16px;
                        margin: 0 auto;
                        padding: 2% 5%;
                        max-width: 800px;
                    }
                    a {
                        color: #000;
                        text-decoration: none;
                    }
                    a:hover { text-decoration: underline; }
                    table {
                        border: none;
                        border-collapse: collapse;
                        width: 100%;
                        font-size:11px;
                    }
                    th { background-color: #c0c0c0; text-align: left; }
                    thead th { border-bottom: 1px solid; }
                    td { padding: 5px; }
                    tr:nth-child(odd) td { background-color: #f5f5f5; }
                    tr:hover td { background-color: #d3e03a; }
                </style>
            </head>
            <body>
                <h1>XML Sitemap</h1>
                <p>This is a sitemap generated by
                    <a href="https://gohugo.io">Hugo</a> to allow search
                    engines to discover this site's content of
		    <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
		    pages.</p>
                <table cellpadding="3">
                <thead>
                    <tr>
                        <th width="75%">URL</th>
                        <th title="Last Modified" width="25%">Last Modified</th>
                    </tr>
                </thead>
                <tbody>
                    <xsl:for-each select="sitemap:urlset/sitemap:url">
                    <tr>
                        <td>
                            <a>
                                <xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute>/<xsl:value-of select="substring-after(substring-after(sitemap:loc, '//'), '/')" />
                            </a>
                        </td>
                        <td>
                            <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                        </td>
                    </tr>
                    </xsl:for-each>
                </tbody>
                </table>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
